name: CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install composer and phpunit
        uses: nick-zh/composer-php@master
        with:
          action: 'require --dev phpunit/phpunit ^9'
      - name: Test app
        uses: nick-zh/composer-php@master
        with:
          action: './vendor/bin/phpunit tests'
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
