name: CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nanasess/composer-installer-action@master
      - run: composer install
      - name: Test app
        run: ./vendor/bin/phpunit --log-junit test/phpunit/_junit/junit.xml -d memory_limit=512M --bootstrap src/autoload.php tests
      - name: Upload test results
        uses: actions/upload-artifact@v2.1.3
        with:
          name: test-results
          path: test/phpunit/_junit/*
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
