name: CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install composer and phpunit
        uses: nick-zh/composer-php@master
        with:
          action: 'install'
      - name: Test app
        run: ./vendor/bin/phpunit --log-junit test/phpunit/_junit/junit.xml -d memory_limit=512M --bootstrap src/autoload.php tests
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
